; Enable per-container with XDEBUG_MODE=debug (see docker-compose.yml).
xdebug.mode = ${XDEBUG_MODE}
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.start_with_request = yes
xdebug.idekey = PHPSTORM
xdebug.log_level = 0
